spring:
  datasource:
    url: jdbc:postgresql://db:5432/geo
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 8080

